// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTiZIKL3RT-jLJRWsg_x0gNW_YWgI63E',
    appId: '1:457152352569:web:36712a75a95f26eb0118e8',
    messagingSenderId: '457152352569',
    projectId: 'gang-aeabb',
    authDomain: 'gang-aeabb.firebaseapp.com',
    storageBucket: 'gang-aeabb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wt-BFJ6GWQ96XSYjwE3sxTvu4RFlO3U',
    appId: '1:457152352569:android:2489b35afcf441ef0118e8',
    messagingSenderId: '457152352569',
    projectId: 'gang-aeabb',
    storageBucket: 'gang-aeabb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJU_-Fg8KIxe1-JFA9WXA1jBJT0klK7hc',
    appId: '1:457152352569:ios:858b365f78dba6c00118e8',
    messagingSenderId: '457152352569',
    projectId: 'gang-aeabb',
    storageBucket: 'gang-aeabb.appspot.com',
    iosClientId: '457152352569-h206567i72p3ljkh2b6bpv7rs65vg2ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.test123.storeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJU_-Fg8KIxe1-JFA9WXA1jBJT0klK7hc',
    appId: '1:457152352569:ios:c61643fa95290b2c0118e8',
    messagingSenderId: '457152352569',
    projectId: 'gang-aeabb',
    storageBucket: 'gang-aeabb.appspot.com',
    iosClientId: '457152352569-3ep6iiqqtpn3n9nmpul1kn36jrtfoo6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeProject',
  );
}
